In [1]:
import pandas as pd

In [2]:
fleni100_match = pd.read_csv("~/Downloads/Fleni/fleni100/match.csv")
fleni100_match

     Unnamed: 0  Unnamed: 0.1                                       anon_id  \
0             0             0  601894e9-7192ca44-617903f9-b7775028-b7db3c01
1             1             1                                           NaN
2             2             2  26f052fa-48d0929f-43515de0-ab857928-4ee712ec
3             3             3  9c673f58-f5bfbaf0-ff226082-410ef24e-e7d8ff4a
4             4             4  0f5ab5b2-c7051e97-42563753-f7f14410-29b463dd
..          ...           ...                                           ...
234         234           255  50b4f5c1-43cbe80d-0d499cc4-525a4752-cb02a377
235         235           256  f301e2e5-ef504c7a-adfe1c95-ef3b1c97-75b21599
236         236           257  c0ed3dcd-9c7e8e50-067ce990-f4417a65-4c5b379f
237         237           258  179ffba1-0dbc255c-ec399ad4-962ed53a-a19a0bff
238         238           259  f1b927dc-db9ba0ef-0e204f32-8ebbc85f-be0fe49a

                            Unnamed: 1  Participant ID                Name  \
0                                  NaN          3370.0             NICOLAS
1    no hay PET. Las RM son desde 2020          8964.0        MARIA TERESA
2                                  NaN         13512.0        MARTA SUSANA
3                                  NaN         13778.0    LIDIA AIDA NOEMI
4                                  NaN         15076.0  ALEJANDRA PATRICIA
..                                 ...             ...                 ...
234                                NaN        703380.0           FERNANDO
235                                NaN        712848.0       LIVIA LUCIANA
236                                NaN        715946.0         PEDRO MARIA
237                                NaN        717824.0            PATRICIO
238                                NaN        718566.0   GUILLERMO AUGUSTO

             Surname                 Nombre T1        AN_MRI    Date_MRI  ...  \
0               RIGA           3D fSPGR-IRprep  9.275000e+12  2013-07-04  ...
1    BILBAO LA VIEJA                       NaN  9.275001e+12         NaN  ...
2           EVRANIAN                  FSPGR 3D  9.275000e+12  2015-06-29  ...
3           WILENSKY   Accelerated Ax IR-FSPGR  9.275001e+12  2019-06-19  ...
4            FONTANA  Accelerated SAG IR-FSPGR  9.275001e+12  2017-08-04  ...
..               ...                       ...           ...         ...  ...
234          BARROS                Ax FSPGR 3D  9.275001e+12  2020-09-11  ...
235             DEON   Accelerated Ax IR-FSPGR  9.275001e+12  2021-01-08  ...
236           PAILHE   Accelerated Ax IR-FSPGR  9.275001e+12  2021-02-11  ...
237           MURPHY               Ax FSPGR 3D  9.275001e+12  2021-05-16  ...
238          BASILIO   Accelerated Ax IR-FSPGR  9.275001e+12  2021-04-03  ...

     gctx-bilat-occipital_rel gctx-bilat-occipital_per  \
0                    0.027904                     11.9
1                         NaN                      NaN
2                    0.036981                     93.7
3                    0.027322                      8.9
4                    0.036672                     83.6
..                        ...                      ...
234                  0.018745                      1.0
235                  0.030842                     44.2
236                  0.031266                     34.0
237                  0.023596                      1.0
238                  0.029793                     24.0

    gctx-bilat-parietal_abs gctx-bilat-parietal_rel gctx-bilat-parietal_per  \
0              1.334525e+16                0.086964                    54.5
1                       NaN                     NaN                     NaN
2              1.157804e+16                0.082528                    35.8
3              9.642489e+15                0.070050                     1.9
4              1.333215e+16                0.088888                    46.6
..                      ...                     ...                     ...
234            1.133951e+14                0.074534                     3.3
235            1.064728e+16                0.076410                    14.9
236            1.367143e+15                0.085687                    36.6
237            1.158759e+16                0.065948                     1.0
238            1.156662e+16                0.074629                     4.5

    gctx-bilat-temporal_abs gctx-bilat-temporal_rel gctx-bilat-temporal_per  \
0              1.035334e+16                0.067468                    36.4
1                       NaN                     NaN                     NaN
2              9.217053e+15                0.065699                    29.7
3              7.203079e+15                0.052328                     1.0
4              9.954130e+15                0.066366                    16.3
..                      ...                     ...                     ...
234            9.487423e+15                0.062360                     5.5
235            8.270453e+15                0.059353                     5.2
236            1.054083e+16                0.066066                    19.6
237            1.034558e+16                0.058879                     1.0
238            1.045008e+16                0.067425                    34.1

    ,anon_id,Unnamed: 1,Participant ID,Name,Surname,Nombre T1,AN_MRI,Date_MRI,Age at diagnostic visit (in years),Diagnostico Presuntivo,Age at death,Age at symptom onset,Sex,Education,APOE4 status,CSF amyloid positivity (yes/no),PET PiB amyloid positivity (yes/no),PET tau positivity (yes/no),FDG PET (hypometabolism profile),diag,unknown_abs,unknown_rel,unknown_per,left-cerebral-white-matter_abs,left-cerebral-white-matter_rel,left-cerebral-white-matter_per,left-cerebral-cortex_abs,left-cerebral-cortex_rel,left-cerebral-cortex_per,supratentorial_ventricles_abs,supratentorial_ventricles_rel,supratentorial_ventricles_per,left-cerebellum-white-matter_abs,left-cerebellum-white-matter_rel,left-cerebellum-white-matter_per,left-cerebellum-cortex_abs,left-cerebellum-cortex_rel,left-cerebellum-cortex_per,left-thalamus-proper*_abs,left-thalamus-proper*_rel,left-thalamus-proper*_per,left-caudate_abs,left-caudate_rel,left-caudate_per,left-putamen_abs,left-putamen_rel,left-putamen_per,left-pallidum_abs,left-pallidum_rel,left-pallidum_per,4th-ventricle_abs,4th-ventricle_rel,4th-ventricle_per,brain-stem_abs,brain-stem_rel,brain-stem_per,left-hippocampus_abs,left-hippocampus_rel,left-hippocampus_per,left-amygdala_abs,left-amygdala_rel,left-amygdala_per,csf-freesurfer_abs,csf-freesurfer_rel,csf-freesurfer_per,left-accumbens-area_abs,left-accumbens-area_rel,left-accumbens-area_per,left-ventraldc_abs,left-ventraldc_rel,left-ventraldc_per,right-cerebral-white-matter_abs,right-cerebral-white-matter_rel,right-cerebral-white-matter_per,right-cerebral-cortex_abs,right-cerebral-cortex_rel,right-cerebral-cortex_per,right-cerebellum-white-matter_abs,right-cerebellum-white-matter_rel,right-cerebellum-white-matter_per,right-cerebellum-cortex_abs,right-cerebellum-cortex_rel,right-cerebellum-cortex_per,right-thalamus-proper*_abs,right-thalamus-proper*_rel,right-thalamus-proper*_per,right-caudate_abs,right-caudate_rel,right-caudate_per,right-putamen_abs,right-putamen_rel,right-putamen_per,right-pallidum_abs,right-pallidum_rel,right-pallidum_per,right-hippocampus_abs,right-hippocampus_rel,right-hippocampus_per,right-amygdala_abs,right-amygdala_rel,right-amygdala_per,right-accumbens-area_abs,right-accumbens-area_rel,right-accumbens-area_per,right-ventraldc_abs,right-ventraldc_rel,right-ventraldc_per,corpus_callosum_abs,corpus_callosum_rel,corpus_callosum_per,ctx-lh-superior+transversetemporal_abs,ctx-lh-superior+transversetemporal_rel,ctx-lh-superior+transversetemporal_per,ctx-lh-cingulo_abs,ctx-lh-cingulo_rel,ctx-lh-cingulo_per,ctx-lh-frontalsuperiorandmiddle_abs,ctx-lh-frontalsuperiorandmiddle_rel,ctx-lh-frontalsuperiorandmiddle_per,ctx-lh-superiorparietal+postcentral_abs,ctx-lh-superiorparietal+postcentral_rel,ctx-lh-superiorparietal+postcentral_per,ctx-lh-inferiorparietal_abs,ctx-lh-inferiorparietal_rel,ctx-lh-inferiorparietal_per,ctx-lh-medialoccipital_abs,ctx-lh-medialoccipital_rel,ctx-lh-medialoccipital_per,ctx-lh-parahippocampal+fusiform+entorhinal_abs,ctx-lh-parahippocampal+fusiform+entorhinal_rel,ctx-lh-parahippocampal+fusiform+entorhinal_per,ctx-lh-middle+inferiortemporal+pole_abs,ctx-lh-middle+inferiortemporal+pole_rel,ctx-lh-middle+inferiortemporal+pole_per,ctx-lh-lateraloccipital_abs,ctx-lh-lateraloccipital_rel,ctx-lh-lateraloccipital_per,ctx-lh-orbitofrontal_abs,ctx-lh-orbitofrontal_rel,ctx-lh-orbitofrontal_per,ctx-lh-precentral+paracentral_abs,ctx-lh-precentral+paracentral_rel,ctx-lh-precentral+paracentral_per,ctx-lh-frontalinferior_abs,ctx-lh-frontalinferior_rel,ctx-lh-frontalinferior_per,ctx-lh-precuneus_abs,ctx-lh-precuneus_rel,ctx-lh-precuneus_per,ctx-lh-insula_abs,ctx-lh-insula_rel,ctx-lh-insula_per,ctx-rh-superior+transversetemporal_abs,ctx-rh-superior+transversetemporal_rel,ctx-rh-superior+transversetemporal_per,ctx-rh-cingulo_abs,ctx-rh-cingulo_rel,ctx-rh-cingulo_per,ctx-rh-frontalsuperiorandmiddle_abs,ctx-rh-frontalsuperiorandmiddle_rel,ctx-rh-frontalsuperiorandmiddle_per,ctx-rh-superiorparietal+postcentral_abs,ctx-rh-superiorparietal+postcentral_rel,ctx-rh-superiorparietal+postcentral_per,ctx-rh-inferiorparietal_abs,ctx-rh-inferiorparietal_rel,ctx-rh-inferiorparietal_per,ctx-rh-medialoccipital_abs,ctx-rh-medialoccipital_rel,ctx-rh-medialoccipital_per,ctx-rh-parahippocampal+fusiform+entorhinal_abs,ctx-rh-parahippocampal+fusiform+entorhinal_rel,ctx-rh-parahippocampal+fusiform+entorhinal_per,ctx-rh-middle+inferiortemporal+pole_abs,ctx-rh-middle+inferiortemporal+pole_rel,ctx-rh-middle+inferiortemporal+pole_per,ctx-rh-lateraloccipital_abs,ctx-rh-lateraloccipital_rel,ctx-rh-lateraloccipital_per,ctx-rh-orbitofrontal_abs,ctx-rh-orbitofrontal_rel,ctx-rh-orbitofrontal_per,ctx-rh-precentral+paracentral_abs,ctx-rh-precentral+paracentral_rel,ctx-rh-precentral+paracentral_per,ctx-rh-frontalinferior_abs,ctx-rh-frontalinferior_rel,ctx-rh-frontalinferior_per,ctx-rh-precuneus_abs,ctx-rh-precuneus_rel,ctx-rh-precuneus_per,ctx-rh-insula_abs,ctx-rh-insula_rel,ctx-rh-insula_per,brain_abs,brain_rel,brain_per,wm_abs,wm_rel,wm_per,gm_abs,gm_rel,gm_per,csf_abs,csf_rel,csf_per,cerebellum_abs,cerebellum_rel,cerebellum_per,bpf_abs,bpf_rel,bpf_per,evans_abs,evans_rel,evans_per,gctx-lh-frontal_abs,gctx-lh-frontal_rel,gctx-lh-frontal_per,gctx-lh-insula_abs,gctx-lh-insula_rel,gctx-lh-insula_per,gctx-lh-occipital_abs,gctx-lh-occipital_rel,gctx-lh-occipital_per,gctx-lh-parietal_abs,gctx-lh-parietal_rel,gctx-lh-parietal_per,gctx-lh-temporal_abs,gctx-lh-temporal_rel,gctx-lh-temporal_per,gctx-rh-frontal_abs,gctx-rh-frontal_rel,gctx-rh-frontal_per,gctx-rh-insula_abs,gctx-rh-insula_rel,gctx-rh-insula_per,gctx-rh-occipital_abs,gctx-rh-occipital_rel,gctx-rh-occipital_per,gctx-rh-parietal_abs,gctx-rh-parietal_rel,gctx-rh-parietal_per,gctx-rh-temporal_abs,gctx-rh-temporal_rel,gctx-rh-temporal_per,gctx-bilat-frontal_abs,gctx-bilat-frontal_rel,gctx-bilat-frontal_per,gctx-bilat-insula_abs,gctx-bilat-insula_rel,gctx-bilat-insula_per,gctx-bilat-occipital_abs,gctx-bilat-occipital_rel,gctx-bilat-occipital_per,gctx-bilat-parietal_abs,gctx-bilat-parietal_rel,gctx-bilat-parietal_per,gctx-bilat-temporal_abs,gctx-bilat-temporal_rel,gctx-bilat-temporal_per  \
0    0,601894e9-7192ca44-617903f9-b7775028-b7db3c01...
1    1,,no hay PET. Las RM son desde 2020,8964.0,MA...
2    2,26f052fa-48d0929f-43515de0-ab857928-4ee712ec...
3    3,9c673f58-f5bfbaf0-ff226082-410ef24e-e7d8ff4a...
4    4,0f5ab5b2-c7051e97-42563753-f7f14410-29b463dd...
..                                                 ...
234  255,50b4f5c1-43cbe80d-0d499cc4-525a4752-cb02a3...
235  256,f301e2e5-ef504c7a-adfe1c95-ef3b1c97-75b215...
236  257,c0ed3dcd-9c7e8e50-067ce990-f4417a65-4c5b37...
237  258,179ffba1-0dbc255c-ec399ad4-962ed53a-a19a0b...
238  259,f1b927dc-db9ba0ef-0e204f32-8ebbc85f-be0fe4...

                                           pet_id
0    b87479c8-641ec909-8b8effc1-9b58a18a-573f8414
1                                               -
2    e5a4f8b8-f6ad7d45-52b4b6e8-f3ebf6cd-c8e8f25b
3    c96cbd4d-f9cfda98-8bd71bc1-e26e87e3-e25c6d50
4    b172e084-61708876-5cb503da-b65f4f85-e1c4e110
..                                            ...
234                                             -
235                                             -
236                                             -
237                                             -
238                                             -

[239 rows x 264 columns]

In [14]:
list(fleni100_match.columns)

['Unnamed: 0',
 'Unnamed: 0.1',
 'anon_id',
 'Unnamed: 1',
 'Participant ID',
 'Name',
 'Surname',
 'Nombre T1',
 'AN_MRI',
 'Date_MRI',
 'Age at diagnostic visit (in years)',
 'Diagnostico Presuntivo',
 'Age at death',
 'Age at symptom onset',
 'Sex',
 'Education',
 'APOE4 status',
 'CSF amyloid positivity (yes/no)',
 'PET PiB amyloid positivity (yes/no)',
 'PET tau positivity (yes/no)',
 'FDG PET (hypometabolism profile)',
 'diag',
 'unknown_abs',
 'unknown_rel',
 'unknown_per',
 'left-cerebral-white-matter_abs',
 'left-cerebral-white-matter_rel',
 'left-cerebral-white-matter_per',
 'left-cerebral-cortex_abs',
 'left-cerebral-cortex_rel',
 'left-cerebral-cortex_per',
 'supratentorial_ventricles_abs',
 'supratentorial_ventricles_rel',
 'supratentorial_ventricles_per',
 'left-cerebellum-white-matter_abs',
 'left-cerebellum-white-matter_rel',
 'left-cerebellum-white-matter_per',
 'left-cerebellum-cortex_abs',
 'left-cerebellum-cortex_rel',
 'left-cerebellum-cortex_per',
 'left-thalamus-proper*_abs',
 'left-thalamus-proper*_rel',
 'left-thalamus-proper*_per',
 'left-caudate_abs',
 'left-caudate_rel',
 'left-caudate_per',
 'left-putamen_abs',
 'left-putamen_rel',
 'left-putamen_per',
 'left-pallidum_abs',
 'left-pallidum_rel',
 'left-pallidum_per',
 '4th-ventricle_abs',
 '4th-ventricle_rel',
 '4th-ventricle_per',
 'brain-stem_abs',
 'brain-stem_rel',
 'brain-stem_per',
 'left-hippocampus_abs',
 'left-hippocampus_rel',
 'left-hippocampus_per',
 'left-amygdala_abs',
 'left-amygdala_rel',
 'left-amygdala_per',
 'csf-freesurfer_abs',
 'csf-freesurfer_rel',
 'csf-freesurfer_per',
 'left-accumbens-area_abs',
 'left-accumbens-area_rel',
 'left-accumbens-area_per',
 'left-ventraldc_abs',
 'left-ventraldc_rel',
 'left-ventraldc_per',
 'right-cerebral-white-matter_abs',
 'right-cerebral-white-matter_rel',
 'right-cerebral-white-matter_per',
 'right-cerebral-cortex_abs',
 'right-cerebral-cortex_rel',
 'right-cerebral-cortex_per',
 'right-cerebellum-white-matter_abs',
 'right-cerebellum-white-matter_rel',
 'right-cerebellum-white-matter_per',
 'right-cerebellum-cortex_abs',
 'right-cerebellum-cortex_rel',
 'right-cerebellum-cortex_per',
 'right-thalamus-proper*_abs',
 'right-thalamus-proper*_rel',
 'right-thalamus-proper*_per',
 'right-caudate_abs',
 'right-caudate_rel',
 'right-caudate_per',
 'right-putamen_abs',
 'right-putamen_rel',
 'right-putamen_per',
 'right-pallidum_abs',
 'right-pallidum_rel',
 'right-pallidum_per',
 'right-hippocampus_abs',
 'right-hippocampus_rel',
 'right-hippocampus_per',
 'right-amygdala_abs',
 'right-amygdala_rel',
 'right-amygdala_per',
 'right-accumbens-area_abs',
 'right-accumbens-area_rel',
 'right-accumbens-area_per',
 'right-ventraldc_abs',
 'right-ventraldc_rel',
 'right-ventraldc_per',
 'corpus_callosum_abs',
 'corpus_callosum_rel',
 'corpus_callosum_per',
 'ctx-lh-superior+transversetemporal_abs',
 'ctx-lh-superior+transversetemporal_rel',
 'ctx-lh-superior+transversetemporal_per',
 'ctx-lh-cingulo_abs',
 'ctx-lh-cingulo_rel',
 'ctx-lh-cingulo_per',
 'ctx-lh-frontalsuperiorandmiddle_abs',
 'ctx-lh-frontalsuperiorandmiddle_rel',
 'ctx-lh-frontalsuperiorandmiddle_per',
 'ctx-lh-superiorparietal+postcentral_abs',
 'ctx-lh-superiorparietal+postcentral_rel',
 'ctx-lh-superiorparietal+postcentral_per',
 'ctx-lh-inferiorparietal_abs',
 'ctx-lh-inferiorparietal_rel',
 'ctx-lh-inferiorparietal_per',
 'ctx-lh-medialoccipital_abs',
 'ctx-lh-medialoccipital_rel',
 'ctx-lh-medialoccipital_per',
 'ctx-lh-parahippocampal+fusiform+entorhinal_abs',
 'ctx-lh-parahippocampal+fusiform+entorhinal_rel',
 'ctx-lh-parahippocampal+fusiform+entorhinal_per',
 'ctx-lh-middle+inferiortemporal+pole_abs',
 'ctx-lh-middle+inferiortemporal+pole_rel',
 'ctx-lh-middle+inferiortemporal+pole_per',
 'ctx-lh-lateraloccipital_abs',
 'ctx-lh-lateraloccipital_rel',
 'ctx-lh-lateraloccipital_per',
 'ctx-lh-orbitofrontal_abs',
 'ctx-lh-orbitofrontal_rel',
 'ctx-lh-orbitofrontal_per',
 'ctx-lh-precentral+paracentral_abs',
 'ctx-lh-precentral+paracentral_rel',
 'ctx-lh-precentral+paracentral_per',
 'ctx-lh-frontalinferior_abs',
 'ctx-lh-frontalinferior_rel',
 'ctx-lh-frontalinferior_per',
 'ctx-lh-precuneus_abs',
 'ctx-lh-precuneus_rel',
 'ctx-lh-precuneus_per',
 'ctx-lh-insula_abs',
 'ctx-lh-insula_rel',
 'ctx-lh-insula_per',
 'ctx-rh-superior+transversetemporal_abs',
 'ctx-rh-superior+transversetemporal_rel',
 'ctx-rh-superior+transversetemporal_per',
 'ctx-rh-cingulo_abs',
 'ctx-rh-cingulo_rel',
 'ctx-rh-cingulo_per',
 'ctx-rh-frontalsuperiorandmiddle_abs',
 'ctx-rh-frontalsuperiorandmiddle_rel',
 'ctx-rh-frontalsuperiorandmiddle_per',
 'ctx-rh-superiorparietal+postcentral_abs',
 'ctx-rh-superiorparietal+postcentral_rel',
 'ctx-rh-superiorparietal+postcentral_per',
 'ctx-rh-inferiorparietal_abs',
 'ctx-rh-inferiorparietal_rel',
 'ctx-rh-inferiorparietal_per',
 'ctx-rh-medialoccipital_abs',
 'ctx-rh-medialoccipital_rel',
 'ctx-rh-medialoccipital_per',
 'ctx-rh-parahippocampal+fusiform+entorhinal_abs',
 'ctx-rh-parahippocampal+fusiform+entorhinal_rel',
 'ctx-rh-parahippocampal+fusiform+entorhinal_per',
 'ctx-rh-middle+inferiortemporal+pole_abs',
 'ctx-rh-middle+inferiortemporal+pole_rel',
 'ctx-rh-middle+inferiortemporal+pole_per',
 'ctx-rh-lateraloccipital_abs',
 'ctx-rh-lateraloccipital_rel',
 'ctx-rh-lateraloccipital_per',
 'ctx-rh-orbitofrontal_abs',
 'ctx-rh-orbitofrontal_rel',
 'ctx-rh-orbitofrontal_per',
 'ctx-rh-precentral+paracentral_abs',
 'ctx-rh-precentral+paracentral_rel',
 'ctx-rh-precentral+paracentral_per',
 'ctx-rh-frontalinferior_abs',
 'ctx-rh-frontalinferior_rel',
 'ctx-rh-frontalinferior_per',
 'ctx-rh-precuneus_abs',
 'ctx-rh-precuneus_rel',
 'ctx-rh-precuneus_per',
 'ctx-rh-insula_abs',
 'ctx-rh-insula_rel',
 'ctx-rh-insula_per',
 'brain_abs',
 'brain_rel',
 'brain_per',
 'wm_abs',
 'wm_rel',
 'wm_per',
 'gm_abs',
 'gm_rel',
 'gm_per',
 'csf_abs',
 'csf_rel',
 'csf_per',
 'cerebellum_abs',
 'cerebellum_rel',
 'cerebellum_per',
 'bpf_abs',
 'bpf_rel',
 'bpf_per',
 'evans_abs',
 'evans_rel',
 'evans_per',
 'gctx-lh-frontal_abs',
 'gctx-lh-frontal_rel',
 'gctx-lh-frontal_per',
 'gctx-lh-insula_abs',
 'gctx-lh-insula_rel',
 'gctx-lh-insula_per',
 'gctx-lh-occipital_abs',
 'gctx-lh-occipital_rel',
 'gctx-lh-occipital_per',
 'gctx-lh-parietal_abs',
 'gctx-lh-parietal_rel',
 'gctx-lh-parietal_per',
 'gctx-lh-temporal_abs',
 'gctx-lh-temporal_rel',
 'gctx-lh-temporal_per',
 'gctx-rh-frontal_abs',
 'gctx-rh-frontal_rel',
 'gctx-rh-frontal_per',
 'gctx-rh-insula_abs',
 'gctx-rh-insula_rel',
 'gctx-rh-insula_per',
 'gctx-rh-occipital_abs',
 'gctx-rh-occipital_rel',
 'gctx-rh-occipital_per',
 'gctx-rh-parietal_abs',
 'gctx-rh-parietal_rel',
 'gctx-rh-parietal_per',
 'gctx-rh-temporal_abs',
 'gctx-rh-temporal_rel',
 'gctx-rh-temporal_per',
 'gctx-bilat-frontal_abs',
 'gctx-bilat-frontal_rel',
 'gctx-bilat-frontal_per',
 'gctx-bilat-insula_abs',
 'gctx-bilat-insula_rel',
 'gctx-bilat-insula_per',
 'gctx-bilat-occipital_abs',
 'gctx-bilat-occipital_rel',
 'gctx-bilat-occipital_per',
 'gctx-bilat-parietal_abs',
 'gctx-bilat-parietal_rel',
 'gctx-bilat-parietal_per',
 'gctx-bilat-temporal_abs',
 'gctx-bilat-temporal_rel',
 'gctx-bilat-temporal_per',
 ',anon_id,Unnamed: 1,Participant ID,Name,Surname,Nombre T1,AN_MRI,Date_MRI,Age at diagnostic visit (in years),Diagnostico Presuntivo,Age at death,Age at symptom onset,Sex,Education,APOE4 status,CSF amyloid positivity (yes/no),PET PiB amyloid positivity (yes/no),PET tau positivity (yes/no),FDG PET (hypometabolism profile),diag,unknown_abs,unknown_rel,unknown_per,left-cerebral-white-matter_abs,left-cerebral-white-matter_rel,left-cerebral-white-matter_per,left-cerebral-cortex_abs,left-cerebral-cortex_rel,left-cerebral-cortex_per,supratentorial_ventricles_abs,supratentorial_ventricles_rel,supratentorial_ventricles_per,left-cerebellum-white-matter_abs,left-cerebellum-white-matter_rel,left-cerebellum-white-matter_per,left-cerebellum-cortex_abs,left-cerebellum-cortex_rel,left-cerebellum-cortex_per,left-thalamus-proper*_abs,left-thalamus-proper*_rel,left-thalamus-proper*_per,left-caudate_abs,left-caudate_rel,left-caudate_per,left-putamen_abs,left-putamen_rel,left-putamen_per,left-pallidum_abs,left-pallidum_rel,left-pallidum_per,4th-ventricle_abs,4th-ventricle_rel,4th-ventricle_per,brain-stem_abs,brain-stem_rel,brain-stem_per,left-hippocampus_abs,left-hippocampus_rel,left-hippocampus_per,left-amygdala_abs,left-amygdala_rel,left-amygdala_per,csf-freesurfer_abs,csf-freesurfer_rel,csf-freesurfer_per,left-accumbens-area_abs,left-accumbens-area_rel,left-accumbens-area_per,left-ventraldc_abs,left-ventraldc_rel,left-ventraldc_per,right-cerebral-white-matter_abs,right-cerebral-white-matter_rel,right-cerebral-white-matter_per,right-cerebral-cortex_abs,right-cerebral-cortex_rel,right-cerebral-cortex_per,right-cerebellum-white-matter_abs,right-cerebellum-white-matter_rel,right-cerebellum-white-matter_per,right-cerebellum-cortex_abs,right-cerebellum-cortex_rel,right-cerebellum-cortex_per,right-thalamus-proper*_abs,right-thalamus-proper*_rel,right-thalamus-proper*_per,right-caudate_abs,right-caudate_rel,right-caudate_per,right-putamen_abs,right-putamen_rel,right-putamen_per,right-pallidum_abs,right-pallidum_rel,right-pallidum_per,right-hippocampus_abs,right-hippocampus_rel,right-hippocampus_per,right-amygdala_abs,right-amygdala_rel,right-amygdala_per,right-accumbens-area_abs,right-accumbens-area_rel,right-accumbens-area_per,right-ventraldc_abs,right-ventraldc_rel,right-ventraldc_per,corpus_callosum_abs,corpus_callosum_rel,corpus_callosum_per,ctx-lh-superior+transversetemporal_abs,ctx-lh-superior+transversetemporal_rel,ctx-lh-superior+transversetemporal_per,ctx-lh-cingulo_abs,ctx-lh-cingulo_rel,ctx-lh-cingulo_per,ctx-lh-frontalsuperiorandmiddle_abs,ctx-lh-frontalsuperiorandmiddle_rel,ctx-lh-frontalsuperiorandmiddle_per,ctx-lh-superiorparietal+postcentral_abs,ctx-lh-superiorparietal+postcentral_rel,ctx-lh-superiorparietal+postcentral_per,ctx-lh-inferiorparietal_abs,ctx-lh-inferiorparietal_rel,ctx-lh-inferiorparietal_per,ctx-lh-medialoccipital_abs,ctx-lh-medialoccipital_rel,ctx-lh-medialoccipital_per,ctx-lh-parahippocampal+fusiform+entorhinal_abs,ctx-lh-parahippocampal+fusiform+entorhinal_rel,ctx-lh-parahippocampal+fusiform+entorhinal_per,ctx-lh-middle+inferiortemporal+pole_abs,ctx-lh-middle+inferiortemporal+pole_rel,ctx-lh-middle+inferiortemporal+pole_per,ctx-lh-lateraloccipital_abs,ctx-lh-lateraloccipital_rel,ctx-lh-lateraloccipital_per,ctx-lh-orbitofrontal_abs,ctx-lh-orbitofrontal_rel,ctx-lh-orbitofrontal_per,ctx-lh-precentral+paracentral_abs,ctx-lh-precentral+paracentral_rel,ctx-lh-precentral+paracentral_per,ctx-lh-frontalinferior_abs,ctx-lh-frontalinferior_rel,ctx-lh-frontalinferior_per,ctx-lh-precuneus_abs,ctx-lh-precuneus_rel,ctx-lh-precuneus_per,ctx-lh-insula_abs,ctx-lh-insula_rel,ctx-lh-insula_per,ctx-rh-superior+transversetemporal_abs,ctx-rh-superior+transversetemporal_rel,ctx-rh-superior+transversetemporal_per,ctx-rh-cingulo_abs,ctx-rh-cingulo_rel,ctx-rh-cingulo_per,ctx-rh-frontalsuperiorandmiddle_abs,ctx-rh-frontalsuperiorandmiddle_rel,ctx-rh-frontalsuperiorandmiddle_per,ctx-rh-superiorparietal+postcentral_abs,ctx-rh-superiorparietal+postcentral_rel,ctx-rh-superiorparietal+postcentral_per,ctx-rh-inferiorparietal_abs,ctx-rh-inferiorparietal_rel,ctx-rh-inferiorparietal_per,ctx-rh-medialoccipital_abs,ctx-rh-medialoccipital_rel,ctx-rh-medialoccipital_per,ctx-rh-parahippocampal+fusiform+entorhinal_abs,ctx-rh-parahippocampal+fusiform+entorhinal_rel,ctx-rh-parahippocampal+fusiform+entorhinal_per,ctx-rh-middle+inferiortemporal+pole_abs,ctx-rh-middle+inferiortemporal+pole_rel,ctx-rh-middle+inferiortemporal+pole_per,ctx-rh-lateraloccipital_abs,ctx-rh-lateraloccipital_rel,ctx-rh-lateraloccipital_per,ctx-rh-orbitofrontal_abs,ctx-rh-orbitofrontal_rel,ctx-rh-orbitofrontal_per,ctx-rh-precentral+paracentral_abs,ctx-rh-precentral+paracentral_rel,ctx-rh-precentral+paracentral_per,ctx-rh-frontalinferior_abs,ctx-rh-frontalinferior_rel,ctx-rh-frontalinferior_per,ctx-rh-precuneus_abs,ctx-rh-precuneus_rel,ctx-rh-precuneus_per,ctx-rh-insula_abs,ctx-rh-insula_rel,ctx-rh-insula_per,brain_abs,brain_rel,brain_per,wm_abs,wm_rel,wm_per,gm_abs,gm_rel,gm_per,csf_abs,csf_rel,csf_per,cerebellum_abs,cerebellum_rel,cerebellum_per,bpf_abs,bpf_rel,bpf_per,evans_abs,evans_rel,evans_per,gctx-lh-frontal_abs,gctx-lh-frontal_rel,gctx-lh-frontal_per,gctx-lh-insula_abs,gctx-lh-insula_rel,gctx-lh-insula_per,gctx-lh-occipital_abs,gctx-lh-occipital_rel,gctx-lh-occipital_per,gctx-lh-parietal_abs,gctx-lh-parietal_rel,gctx-lh-parietal_per,gctx-lh-temporal_abs,gctx-lh-temporal_rel,gctx-lh-temporal_per,gctx-rh-frontal_abs,gctx-rh-frontal_rel,gctx-rh-frontal_per,gctx-rh-insula_abs,gctx-rh-insula_rel,gctx-rh-insula_per,gctx-rh-occipital_abs,gctx-rh-occipital_rel,gctx-rh-occipital_per,gctx-rh-parietal_abs,gctx-rh-parietal_rel,gctx-rh-parietal_per,gctx-rh-temporal_abs,gctx-rh-temporal_rel,gctx-rh-temporal_per,gctx-bilat-frontal_abs,gctx-bilat-frontal_rel,gctx-bilat-frontal_per,gctx-bilat-insula_abs,gctx-bilat-insula_rel,gctx-bilat-insula_per,gctx-bilat-occipital_abs,gctx-bilat-occipital_rel,gctx-bilat-occipital_per,gctx-bilat-parietal_abs,gctx-bilat-parietal_rel,gctx-bilat-parietal_per,gctx-bilat-temporal_abs,gctx-bilat-temporal_rel,gctx-bilat-temporal_per',
 'pet_id']

In [19]:
fleni100 = fleni100_match[
    [
        "pet_id",
        "diag",
        "CSF amyloid positivity (yes/no)",
        "PET PiB amyloid positivity (yes/no)",
    ]
]
fleni100 = fleni100[fleni100["pet_id"] != "-"]

In [21]:
fleni100["CSF amyloid positivity (yes/no)"].value_counts()

CSF amyloid positivity (yes/no)
Yes          15
Normal        8
Sin Datos     1
Name: count, dtype: int64

In [22]:
fleni100["CSF"] = fleni100["CSF amyloid positivity (yes/no)"] == "Yes"

In [23]:
fleni100["PET PiB amyloid positivity (yes/no)"].value_counts()

PET PiB amyloid positivity (yes/no)
Yes    65
No     51
Name: count, dtype: int64

In [24]:
fleni100["PET PiB"] = fleni100["PET PiB amyloid positivity (yes/no)"] == "Yes"

In [26]:

# correlation between "diag", "csf" and "pet pib"
fleni100[
    [
        "diag",
        "CSF",
        "PET PiB",
    ]
].corr()

             diag       CSF   PET PiB
diag     1.000000  0.298516  0.870780
CSF      0.298516  1.000000  0.003642
PET PiB  0.870780  0.003642  1.000000

In [37]:
fleni100

,pet_id,diag,CSF amyloid positivity (yes/no),PET PiB amyloid positivity (yes/no),CSF,PET PiB
0,b87479c8-641ec909-8b8effc1-9b58a18a-573f8414,1.0,Yes,No,True,False
2,e5a4f8b8-f6ad7d45-52b4b6e8-f3ebf6cd-c8e8f25b,1.0,NaN,Yes,False,True
3,c96cbd4d-f9cfda98-8bd71bc1-e26e87e3-e25c6d50,1.0,NaN,Yes,False,True
4,b172e084-61708876-5cb503da-b65f4f85-e1c4e110,1.0,Yes,Yes,True,True
6,ad80ea14-f27dad6f-3e12c1f0-2993bcc3-4cb99a80,0.0,NaN,No,False,False
...,...,...,...,...,...,...
225,a4dc5f48-55b6fe7b-95df4cc2-d1a9765f-acf114ce,1.0,NaN,Yes,False,True
226,24fa2c1d-1218de8c-c96d25cb-28e77c7a-89e0c0a4,1.0,NaN,Yes,False,True
231,1541a4b6-f7f308c1-9e017a0a-d247bc16-e3117067,1.0,NaN,Yes,False,True
232,5e28bc57-30e1abd2-a0a7d856-4fc1af1e-5bee10d2,1.0,Yes,No,True,False
233,625ddb3f-6b6adb4a-0653c1b1-1e566cc8-3fe2fab5,1.0,NaN,Yes,False,True

In [29]:
!pip install -U openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]━━ 1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [30]:
fleni600_og = pd.read_excel(
    "~/Downloads/Fleni/fleni600/fleni600_original.xlsx",
)
fleni600_og

,Unnamed: 0,StudyDate,anon_id,PatientID,PatientSex,PatientName,Conclusion,Diagnóstico
0,238,20200825,625ddb3f-6b6adb4a-0653c1b1-1e566cc8-3fe2fab5,702774,M,WANGER^WALTER ROBERTO,-ALa distribución espacial de los hallazgos ...,AD
1,234,20201006,c45568f2-c860c13b-ddabe3eb-7bc72f65-dc96ba33,701575,F,RUBIO^MARIA ALEJANDRA,-ALa distribución espacial de los hallazgos ...,AD
2,435,20190426,b0e1b100-f29d020b-07fb9c16-bb41abdc-43d7b0e8,597445,F,BRALO^ALICIA ESTER,-ALa distribución espacial de los hallazgos ...,AD
3,247,20200804,ee1769c5-189b12d7-187a454e-f13189f4-19f82052,554900,M,LOBOS^ANIBAL PEDRO,Amiloidosis cortical difusa en el presente e...,AD
4,387,20190718,ec84b311-4f89bd80-bfd691ed-bb1cd2f4-c700b95c,655037,F,SANCHEZ^MARCELA ADRIANA,Amiloidosis cortical difusa en el presente e...,AD
...,...,...,...,...,...,...,...,...
1610,1610,20130215,394f9c0f-407407df-924d39d5-385898a0-103e5c19,474496,M,RIVAROLA^HUGO EUGENIO,NaN,NaN
1611,1611,20130221,2137659d-aa1d903d-beb5a549-8d252a72-a903e6a2,266991,F,BER^PATRICIA,NaN,NaN
1612,1612,20130227,291a10ba-ca622d77-7eb09271-f0948eeb-745ef704,475954,M,GALOSI JUAN CARLOS,NaN,NaN
1613,1613,20130205,667cb287-d9eee39e-e4a18254-beebf4c8-52aa0723,188881,F,VENANCIO^MARIA ALEJANDRA,NaN,NaN
1614,1614,20130123,419fb7ba-a7646e04-81c8b19d-ac69325b-95b07fef,469780,F,MARTIN^MARIA LUISA,NaN,NaN

In [36]:
fleni600 = fleni600_og[
    [
        "Unnamed: 0",
        "Diagnóstico",
    ]
]

fleni600 = fleni600[fleni600["Diagnóstico"].notna()]
fleni600 = fleni600.rename(
    columns={
        "Unnamed: 0": "pet_id",
        "Diagnóstico": "diag",
    }
)

fleni600

     pet_id    diag
0       238      AD
1       234      AD
2       435      AD
3       247      AD
4       387      AD
..      ...     ...
633     165  non-AD
634     167  non-AD
635     205  non-AD
636     926  non-AD
637     951  non-AD

[638 rows x 2 columns]

In [ ]:
import os
import glob

In [53]:
fleni100_nifti_files_dir = "~/Downloads/Fleni/fleni100/entelai-fleni-pet-base-diferencial/panania/Neuro/fleni_pet_en_base_dif/fleni100/"

fleni100_nifti_files = os.listdir(
    os.path.expanduser(fleni100_nifti_files_dir)
)

fleni100_nifti_files_ids = [
    os.path.splitext(os.path.splitext(os.path.basename(f))[0])[0] for f in fleni100_nifti_files
]

fleni100_nifti_files_ids = set(fleni100_nifti_files_ids)

fleni100_ids = set(fleni100["pet_id"].values)

len(fleni100_nifti_files_ids), len(fleni100_ids), len(fleni100_nifti_files_ids.intersection(fleni100_ids))

(115, 115, 115)

In [60]:
fleni600_nifti_files_dir = "~/Downloads/Fleni/fleni600/converted_niftis/"
fleni600_nifti_files = os.listdir(
    os.path.expanduser(fleni600_nifti_files_dir)
)
fleni600_nifti_files_ids = [
    os.path.splitext(os.path.splitext(os.path.basename(f))[0])[0].split("_")[1] for f in
    fleni600_nifti_files
]
fleni600_nifti_files_ids = set(fleni600_nifti_files_ids)

fleni600_ids = set(fleni600["pet_id"].astype(str).values)
len(fleni600_nifti_files_ids), len(fleni600_ids), len(fleni600_nifti_files_ids.intersection(fleni600_ids))

(1328, 638, 533)